### ISSUE TITLE
incompatible with Apple M3 chip 

### ISSUE THREAD

**Issue by geofly1985** [Genentech/spex#2]
Hi, I found an issue about the incompatibility with Apple M3 chip,

when I tried to run `./app_demo_silicon.sh up`, it returns error indicating CPU type isn't compatible. 
![Screenshot 2024-08-27 at 11 02 19 AM](https://github.com/user-attachments/assets/c645cb02-6dd6-4c8f-93e8-df2dc1d4af15)

I did installed docker version that support apple silicon:  https://www.docker.com/products/docker-desktop/

Best, 
Xiao

**Comment by zverozabr** [comment]
Try uninstalling and reinstalling Docker Desktop using this link:
https://desktop.docker.com/mac/main/arm64/Docker.dmg

Alternatively, install OrbStack, which performs similar functions:
OrbStack Download (ARM64)
https://cdn-updates.orbstack.dev/arm64/OrbStack_v1.7.0_17311_arm64.dmg

Then, try the installation again.
Has something happened with Docker?

**Comment by zverozabr** [comment]
start docker application without run any scripts before, it will be show something like 
![image](https://github.com/user-attachments/assets/1213ceff-b80d-4433-94b1-a94141985ad7)
this

**Comment by zverozabr** [comment]
all okay?,
 i have same issue today, but reinstall apple silicon version helps me

**Comment by zverozabr** [comment]
I tested and tested and found that some of the scripts work with an error and decided to remove support for Apple Silicon from the project(not enough sources for test every platform), so I kindly ask you to start using spex on a Windows or Ubuntu computer, the scope of tested functionality is much larger there, I apologize for misleading you about the fact that the ARM architecture is supported.
