### ISSUE TITLE
Cannot login from another device

### ISSUE THREAD

**Issue by tabatsky** [Genentech/spex#4]
Login working fine via localhost.
But when I'm trying to open http://<my ip address>:3000 from another device, it is correctly displaying the login page, but I have the "username or password is not matched" error.

**Comment by zverozabr** [comment]
this version was made for testing on one local machine, if you need to deploy within a local network,

it is better to raise but much more difficult
https://github.com/genentech/spex_bundle
from this repository the entire cascade of microservices.

If you need access, I would recommend raising another copy from this repository on the second machine from which you are trying to enter, this is more user friendly than the one suggested above.
